services:
  api:
    image: inventoryapi-api:prod

    build:
      context: .
      dockerfile: Dockerfile
      target: production

    container_name: inventory_api_prod

    ports:
      - "8000:8000"

    environment:
      PYTHONUNBUFFERED: "1"
      APP_ENV: production

    init: true