services:
  api:
    image: inventory_api_dev
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: inventory_api_dev
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - inventory_data:/data
    environment:
      - PYTHONUNBUFFERED=1
      - APP_ENV=development
      - DATABASE_URL=sqlite:////data/inventory.db
    # Permite mandar señales SIGINT/SIGTERM limpias a Uvicorn
    init: true

volumes:
  inventory_data: