[project]
name = "inventoryapi"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "risolisosatiagodavid", email = "risolisosatiagodavid@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.141.1",
    "uvicorn>=0.52.4",
]

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false

[dependency-groups]
dev = [
    "commitizen>=4.18.1",
    "httpx>=0.28.1",
    "pytest>=9.1.1",
]

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "semver"
version_provider = "pep621"
update_changelog_on_bump = true
changelog_file = "CHANGELOG.md"